
interface _GlobalComponents {
      'Counter': typeof import("../components/Counter.vue")['default']
    'DarkToggle': typeof import("../components/DarkToggle.vue")['default']
    'Footer': typeof import("../components/Footer.vue")['default']
    'InputEntry': typeof import("../components/InputEntry.vue")['default']
    'Logos': typeof import("../components/Logos.vue")['default']
    'PageView': typeof import("../components/PageView.vue")['default']
    'UnoIcon': typeof import("../node_modules/.pnpm/@unocss+nuxt@0.60.4_postcss@8.4.38_rollup@2.79.1_vite@5.2.12_webpack@5.91.0/node_modules/@unocss/nuxt/runtime/UnoIcon.vue")['default']
    'NuxtWelcome': typeof import("../node_modules/.pnpm/@nuxt+ui-templates@1.3.4/node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
    'NuxtLayout': typeof import("../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.8.0_@unocss+reset@0.60.4_eslint@9.4.0_floating-vue@5.2.2_rol_kz5sis3zuyiqyo5au5yoh7bo4q/node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'NuxtErrorBoundary': typeof import("../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.8.0_@unocss+reset@0.60.4_eslint@9.4.0_floating-vue@5.2.2_rol_kz5sis3zuyiqyo5au5yoh7bo4q/node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'ClientOnly': typeof import("../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.8.0_@unocss+reset@0.60.4_eslint@9.4.0_floating-vue@5.2.2_rol_kz5sis3zuyiqyo5au5yoh7bo4q/node_modules/nuxt/dist/app/components/client-only")['default']
    'DevOnly': typeof import("../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.8.0_@unocss+reset@0.60.4_eslint@9.4.0_floating-vue@5.2.2_rol_kz5sis3zuyiqyo5au5yoh7bo4q/node_modules/nuxt/dist/app/components/dev-only")['default']
    'ServerPlaceholder': typeof import("../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.8.0_@unocss+reset@0.60.4_eslint@9.4.0_floating-vue@5.2.2_rol_kz5sis3zuyiqyo5au5yoh7bo4q/node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'NuxtLink': typeof import("../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.8.0_@unocss+reset@0.60.4_eslint@9.4.0_floating-vue@5.2.2_rol_kz5sis3zuyiqyo5au5yoh7bo4q/node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'NuxtLoadingIndicator': typeof import("../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.8.0_@unocss+reset@0.60.4_eslint@9.4.0_floating-vue@5.2.2_rol_kz5sis3zuyiqyo5au5yoh7bo4q/node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'NuxtIsland': typeof import("../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.8.0_@unocss+reset@0.60.4_eslint@9.4.0_floating-vue@5.2.2_rol_kz5sis3zuyiqyo5au5yoh7bo4q/node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'NuxtImg': typeof import("../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.8.0_@unocss+reset@0.60.4_eslint@9.4.0_floating-vue@5.2.2_rol_kz5sis3zuyiqyo5au5yoh7bo4q/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'NuxtPicture': typeof import("../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.8.0_@unocss+reset@0.60.4_eslint@9.4.0_floating-vue@5.2.2_rol_kz5sis3zuyiqyo5au5yoh7bo4q/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'ColorScheme': typeof import("../node_modules/.pnpm/@nuxtjs+color-mode@3.4.1_rollup@2.79.1/node_modules/@nuxtjs/color-mode/dist/runtime/component.vue3.vue")['default']
    'VitePwaManifest': typeof import("../node_modules/.pnpm/@vite-pwa+nuxt@0.7.0_rollup@2.79.1_vite@5.2.12_workbox-build@7.1.1_workbox-window@7.1.0/node_modules/@vite-pwa/nuxt/dist/runtime/components/VitePwaManifest")['default']
    'NuxtPwaManifest': typeof import("../node_modules/.pnpm/@vite-pwa+nuxt@0.7.0_rollup@2.79.1_vite@5.2.12_workbox-build@7.1.1_workbox-window@7.1.0/node_modules/@vite-pwa/nuxt/dist/runtime/components/VitePwaManifest")['default']
    'NuxtPwaAssets': typeof import("../node_modules/.pnpm/@vite-pwa+nuxt@0.7.0_rollup@2.79.1_vite@5.2.12_workbox-build@7.1.1_workbox-window@7.1.0/node_modules/@vite-pwa/nuxt/dist/runtime/components/NuxtPwaAssets")['default']
    'PwaAppleImage': typeof import("../node_modules/.pnpm/@vite-pwa+nuxt@0.7.0_rollup@2.79.1_vite@5.2.12_workbox-build@7.1.1_workbox-window@7.1.0/node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaAppleImage.vue")['default']
    'PwaAppleSplashScreenImage': typeof import("../node_modules/.pnpm/@vite-pwa+nuxt@0.7.0_rollup@2.79.1_vite@5.2.12_workbox-build@7.1.1_workbox-window@7.1.0/node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaAppleSplashScreenImage.vue")['default']
    'PwaFaviconImage': typeof import("../node_modules/.pnpm/@vite-pwa+nuxt@0.7.0_rollup@2.79.1_vite@5.2.12_workbox-build@7.1.1_workbox-window@7.1.0/node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaFaviconImage.vue")['default']
    'PwaMaskableImage': typeof import("../node_modules/.pnpm/@vite-pwa+nuxt@0.7.0_rollup@2.79.1_vite@5.2.12_workbox-build@7.1.1_workbox-window@7.1.0/node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaMaskableImage.vue")['default']
    'PwaTransparentImage': typeof import("../node_modules/.pnpm/@vite-pwa+nuxt@0.7.0_rollup@2.79.1_vite@5.2.12_workbox-build@7.1.1_workbox-window@7.1.0/node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaTransparentImage.vue")['default']
    'NuxtPage': typeof import("../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.8.0_@unocss+reset@0.60.4_eslint@9.4.0_floating-vue@5.2.2_rol_kz5sis3zuyiqyo5au5yoh7bo4q/node_modules/nuxt/dist/pages/runtime/page")['default']
    'NoScript': typeof import("../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.8.0_@unocss+reset@0.60.4_eslint@9.4.0_floating-vue@5.2.2_rol_kz5sis3zuyiqyo5au5yoh7bo4q/node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'Link': typeof import("../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.8.0_@unocss+reset@0.60.4_eslint@9.4.0_floating-vue@5.2.2_rol_kz5sis3zuyiqyo5au5yoh7bo4q/node_modules/nuxt/dist/head/runtime/components")['Link']
    'Base': typeof import("../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.8.0_@unocss+reset@0.60.4_eslint@9.4.0_floating-vue@5.2.2_rol_kz5sis3zuyiqyo5au5yoh7bo4q/node_modules/nuxt/dist/head/runtime/components")['Base']
    'Title': typeof import("../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.8.0_@unocss+reset@0.60.4_eslint@9.4.0_floating-vue@5.2.2_rol_kz5sis3zuyiqyo5au5yoh7bo4q/node_modules/nuxt/dist/head/runtime/components")['Title']
    'Meta': typeof import("../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.8.0_@unocss+reset@0.60.4_eslint@9.4.0_floating-vue@5.2.2_rol_kz5sis3zuyiqyo5au5yoh7bo4q/node_modules/nuxt/dist/head/runtime/components")['Meta']
    'Style': typeof import("../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.8.0_@unocss+reset@0.60.4_eslint@9.4.0_floating-vue@5.2.2_rol_kz5sis3zuyiqyo5au5yoh7bo4q/node_modules/nuxt/dist/head/runtime/components")['Style']
    'Head': typeof import("../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.8.0_@unocss+reset@0.60.4_eslint@9.4.0_floating-vue@5.2.2_rol_kz5sis3zuyiqyo5au5yoh7bo4q/node_modules/nuxt/dist/head/runtime/components")['Head']
    'Html': typeof import("../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.8.0_@unocss+reset@0.60.4_eslint@9.4.0_floating-vue@5.2.2_rol_kz5sis3zuyiqyo5au5yoh7bo4q/node_modules/nuxt/dist/head/runtime/components")['Html']
    'Body': typeof import("../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.8.0_@unocss+reset@0.60.4_eslint@9.4.0_floating-vue@5.2.2_rol_kz5sis3zuyiqyo5au5yoh7bo4q/node_modules/nuxt/dist/head/runtime/components")['Body']
      'LazyCounter': typeof import("../components/Counter.vue")['default']
    'LazyDarkToggle': typeof import("../components/DarkToggle.vue")['default']
    'LazyFooter': typeof import("../components/Footer.vue")['default']
    'LazyInputEntry': typeof import("../components/InputEntry.vue")['default']
    'LazyLogos': typeof import("../components/Logos.vue")['default']
    'LazyPageView': typeof import("../components/PageView.vue")['default']
    'LazyUnoIcon': typeof import("../node_modules/.pnpm/@unocss+nuxt@0.60.4_postcss@8.4.38_rollup@2.79.1_vite@5.2.12_webpack@5.91.0/node_modules/@unocss/nuxt/runtime/UnoIcon.vue")['default']
    'LazyNuxtWelcome': typeof import("../node_modules/.pnpm/@nuxt+ui-templates@1.3.4/node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
    'LazyNuxtLayout': typeof import("../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.8.0_@unocss+reset@0.60.4_eslint@9.4.0_floating-vue@5.2.2_rol_kz5sis3zuyiqyo5au5yoh7bo4q/node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'LazyNuxtErrorBoundary': typeof import("../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.8.0_@unocss+reset@0.60.4_eslint@9.4.0_floating-vue@5.2.2_rol_kz5sis3zuyiqyo5au5yoh7bo4q/node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'LazyClientOnly': typeof import("../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.8.0_@unocss+reset@0.60.4_eslint@9.4.0_floating-vue@5.2.2_rol_kz5sis3zuyiqyo5au5yoh7bo4q/node_modules/nuxt/dist/app/components/client-only")['default']
    'LazyDevOnly': typeof import("../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.8.0_@unocss+reset@0.60.4_eslint@9.4.0_floating-vue@5.2.2_rol_kz5sis3zuyiqyo5au5yoh7bo4q/node_modules/nuxt/dist/app/components/dev-only")['default']
    'LazyServerPlaceholder': typeof import("../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.8.0_@unocss+reset@0.60.4_eslint@9.4.0_floating-vue@5.2.2_rol_kz5sis3zuyiqyo5au5yoh7bo4q/node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'LazyNuxtLink': typeof import("../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.8.0_@unocss+reset@0.60.4_eslint@9.4.0_floating-vue@5.2.2_rol_kz5sis3zuyiqyo5au5yoh7bo4q/node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'LazyNuxtLoadingIndicator': typeof import("../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.8.0_@unocss+reset@0.60.4_eslint@9.4.0_floating-vue@5.2.2_rol_kz5sis3zuyiqyo5au5yoh7bo4q/node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'LazyNuxtIsland': typeof import("../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.8.0_@unocss+reset@0.60.4_eslint@9.4.0_floating-vue@5.2.2_rol_kz5sis3zuyiqyo5au5yoh7bo4q/node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'LazyNuxtImg': typeof import("../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.8.0_@unocss+reset@0.60.4_eslint@9.4.0_floating-vue@5.2.2_rol_kz5sis3zuyiqyo5au5yoh7bo4q/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'LazyNuxtPicture': typeof import("../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.8.0_@unocss+reset@0.60.4_eslint@9.4.0_floating-vue@5.2.2_rol_kz5sis3zuyiqyo5au5yoh7bo4q/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'LazyColorScheme': typeof import("../node_modules/.pnpm/@nuxtjs+color-mode@3.4.1_rollup@2.79.1/node_modules/@nuxtjs/color-mode/dist/runtime/component.vue3.vue")['default']
    'LazyVitePwaManifest': typeof import("../node_modules/.pnpm/@vite-pwa+nuxt@0.7.0_rollup@2.79.1_vite@5.2.12_workbox-build@7.1.1_workbox-window@7.1.0/node_modules/@vite-pwa/nuxt/dist/runtime/components/VitePwaManifest")['default']
    'LazyNuxtPwaManifest': typeof import("../node_modules/.pnpm/@vite-pwa+nuxt@0.7.0_rollup@2.79.1_vite@5.2.12_workbox-build@7.1.1_workbox-window@7.1.0/node_modules/@vite-pwa/nuxt/dist/runtime/components/VitePwaManifest")['default']
    'LazyNuxtPwaAssets': typeof import("../node_modules/.pnpm/@vite-pwa+nuxt@0.7.0_rollup@2.79.1_vite@5.2.12_workbox-build@7.1.1_workbox-window@7.1.0/node_modules/@vite-pwa/nuxt/dist/runtime/components/NuxtPwaAssets")['default']
    'LazyPwaAppleImage': typeof import("../node_modules/.pnpm/@vite-pwa+nuxt@0.7.0_rollup@2.79.1_vite@5.2.12_workbox-build@7.1.1_workbox-window@7.1.0/node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaAppleImage.vue")['default']
    'LazyPwaAppleSplashScreenImage': typeof import("../node_modules/.pnpm/@vite-pwa+nuxt@0.7.0_rollup@2.79.1_vite@5.2.12_workbox-build@7.1.1_workbox-window@7.1.0/node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaAppleSplashScreenImage.vue")['default']
    'LazyPwaFaviconImage': typeof import("../node_modules/.pnpm/@vite-pwa+nuxt@0.7.0_rollup@2.79.1_vite@5.2.12_workbox-build@7.1.1_workbox-window@7.1.0/node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaFaviconImage.vue")['default']
    'LazyPwaMaskableImage': typeof import("../node_modules/.pnpm/@vite-pwa+nuxt@0.7.0_rollup@2.79.1_vite@5.2.12_workbox-build@7.1.1_workbox-window@7.1.0/node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaMaskableImage.vue")['default']
    'LazyPwaTransparentImage': typeof import("../node_modules/.pnpm/@vite-pwa+nuxt@0.7.0_rollup@2.79.1_vite@5.2.12_workbox-build@7.1.1_workbox-window@7.1.0/node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaTransparentImage.vue")['default']
    'LazyNuxtPage': typeof import("../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.8.0_@unocss+reset@0.60.4_eslint@9.4.0_floating-vue@5.2.2_rol_kz5sis3zuyiqyo5au5yoh7bo4q/node_modules/nuxt/dist/pages/runtime/page")['default']
    'LazyNoScript': typeof import("../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.8.0_@unocss+reset@0.60.4_eslint@9.4.0_floating-vue@5.2.2_rol_kz5sis3zuyiqyo5au5yoh7bo4q/node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'LazyLink': typeof import("../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.8.0_@unocss+reset@0.60.4_eslint@9.4.0_floating-vue@5.2.2_rol_kz5sis3zuyiqyo5au5yoh7bo4q/node_modules/nuxt/dist/head/runtime/components")['Link']
    'LazyBase': typeof import("../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.8.0_@unocss+reset@0.60.4_eslint@9.4.0_floating-vue@5.2.2_rol_kz5sis3zuyiqyo5au5yoh7bo4q/node_modules/nuxt/dist/head/runtime/components")['Base']
    'LazyTitle': typeof import("../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.8.0_@unocss+reset@0.60.4_eslint@9.4.0_floating-vue@5.2.2_rol_kz5sis3zuyiqyo5au5yoh7bo4q/node_modules/nuxt/dist/head/runtime/components")['Title']
    'LazyMeta': typeof import("../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.8.0_@unocss+reset@0.60.4_eslint@9.4.0_floating-vue@5.2.2_rol_kz5sis3zuyiqyo5au5yoh7bo4q/node_modules/nuxt/dist/head/runtime/components")['Meta']
    'LazyStyle': typeof import("../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.8.0_@unocss+reset@0.60.4_eslint@9.4.0_floating-vue@5.2.2_rol_kz5sis3zuyiqyo5au5yoh7bo4q/node_modules/nuxt/dist/head/runtime/components")['Style']
    'LazyHead': typeof import("../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.8.0_@unocss+reset@0.60.4_eslint@9.4.0_floating-vue@5.2.2_rol_kz5sis3zuyiqyo5au5yoh7bo4q/node_modules/nuxt/dist/head/runtime/components")['Head']
    'LazyHtml': typeof import("../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.8.0_@unocss+reset@0.60.4_eslint@9.4.0_floating-vue@5.2.2_rol_kz5sis3zuyiqyo5au5yoh7bo4q/node_modules/nuxt/dist/head/runtime/components")['Html']
    'LazyBody': typeof import("../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.8.0_@unocss+reset@0.60.4_eslint@9.4.0_floating-vue@5.2.2_rol_kz5sis3zuyiqyo5au5yoh7bo4q/node_modules/nuxt/dist/head/runtime/components")['Body']
}

declare module '@vue/runtime-core' {
  export interface GlobalComponents extends _GlobalComponents { }
}

declare module '@vue/runtime-dom' {
  export interface GlobalComponents extends _GlobalComponents { }
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export const Counter: typeof import("../components/Counter.vue")['default']
export const DarkToggle: typeof import("../components/DarkToggle.vue")['default']
export const Footer: typeof import("../components/Footer.vue")['default']
export const InputEntry: typeof import("../components/InputEntry.vue")['default']
export const Logos: typeof import("../components/Logos.vue")['default']
export const PageView: typeof import("../components/PageView.vue")['default']
export const UnoIcon: typeof import("../node_modules/.pnpm/@unocss+nuxt@0.60.4_postcss@8.4.38_rollup@2.79.1_vite@5.2.12_webpack@5.91.0/node_modules/@unocss/nuxt/runtime/UnoIcon.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/.pnpm/@nuxt+ui-templates@1.3.4/node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
export const NuxtLayout: typeof import("../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.8.0_@unocss+reset@0.60.4_eslint@9.4.0_floating-vue@5.2.2_rol_kz5sis3zuyiqyo5au5yoh7bo4q/node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.8.0_@unocss+reset@0.60.4_eslint@9.4.0_floating-vue@5.2.2_rol_kz5sis3zuyiqyo5au5yoh7bo4q/node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.8.0_@unocss+reset@0.60.4_eslint@9.4.0_floating-vue@5.2.2_rol_kz5sis3zuyiqyo5au5yoh7bo4q/node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.8.0_@unocss+reset@0.60.4_eslint@9.4.0_floating-vue@5.2.2_rol_kz5sis3zuyiqyo5au5yoh7bo4q/node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.8.0_@unocss+reset@0.60.4_eslint@9.4.0_floating-vue@5.2.2_rol_kz5sis3zuyiqyo5au5yoh7bo4q/node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.8.0_@unocss+reset@0.60.4_eslint@9.4.0_floating-vue@5.2.2_rol_kz5sis3zuyiqyo5au5yoh7bo4q/node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.8.0_@unocss+reset@0.60.4_eslint@9.4.0_floating-vue@5.2.2_rol_kz5sis3zuyiqyo5au5yoh7bo4q/node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtIsland: typeof import("../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.8.0_@unocss+reset@0.60.4_eslint@9.4.0_floating-vue@5.2.2_rol_kz5sis3zuyiqyo5au5yoh7bo4q/node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const NuxtImg: typeof import("../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.8.0_@unocss+reset@0.60.4_eslint@9.4.0_floating-vue@5.2.2_rol_kz5sis3zuyiqyo5au5yoh7bo4q/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const NuxtPicture: typeof import("../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.8.0_@unocss+reset@0.60.4_eslint@9.4.0_floating-vue@5.2.2_rol_kz5sis3zuyiqyo5au5yoh7bo4q/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const ColorScheme: typeof import("../node_modules/.pnpm/@nuxtjs+color-mode@3.4.1_rollup@2.79.1/node_modules/@nuxtjs/color-mode/dist/runtime/component.vue3.vue")['default']
export const VitePwaManifest: typeof import("../node_modules/.pnpm/@vite-pwa+nuxt@0.7.0_rollup@2.79.1_vite@5.2.12_workbox-build@7.1.1_workbox-window@7.1.0/node_modules/@vite-pwa/nuxt/dist/runtime/components/VitePwaManifest")['default']
export const NuxtPwaManifest: typeof import("../node_modules/.pnpm/@vite-pwa+nuxt@0.7.0_rollup@2.79.1_vite@5.2.12_workbox-build@7.1.1_workbox-window@7.1.0/node_modules/@vite-pwa/nuxt/dist/runtime/components/VitePwaManifest")['default']
export const NuxtPwaAssets: typeof import("../node_modules/.pnpm/@vite-pwa+nuxt@0.7.0_rollup@2.79.1_vite@5.2.12_workbox-build@7.1.1_workbox-window@7.1.0/node_modules/@vite-pwa/nuxt/dist/runtime/components/NuxtPwaAssets")['default']
export const PwaAppleImage: typeof import("../node_modules/.pnpm/@vite-pwa+nuxt@0.7.0_rollup@2.79.1_vite@5.2.12_workbox-build@7.1.1_workbox-window@7.1.0/node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaAppleImage.vue")['default']
export const PwaAppleSplashScreenImage: typeof import("../node_modules/.pnpm/@vite-pwa+nuxt@0.7.0_rollup@2.79.1_vite@5.2.12_workbox-build@7.1.1_workbox-window@7.1.0/node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaAppleSplashScreenImage.vue")['default']
export const PwaFaviconImage: typeof import("../node_modules/.pnpm/@vite-pwa+nuxt@0.7.0_rollup@2.79.1_vite@5.2.12_workbox-build@7.1.1_workbox-window@7.1.0/node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaFaviconImage.vue")['default']
export const PwaMaskableImage: typeof import("../node_modules/.pnpm/@vite-pwa+nuxt@0.7.0_rollup@2.79.1_vite@5.2.12_workbox-build@7.1.1_workbox-window@7.1.0/node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaMaskableImage.vue")['default']
export const PwaTransparentImage: typeof import("../node_modules/.pnpm/@vite-pwa+nuxt@0.7.0_rollup@2.79.1_vite@5.2.12_workbox-build@7.1.1_workbox-window@7.1.0/node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaTransparentImage.vue")['default']
export const NuxtPage: typeof import("../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.8.0_@unocss+reset@0.60.4_eslint@9.4.0_floating-vue@5.2.2_rol_kz5sis3zuyiqyo5au5yoh7bo4q/node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.8.0_@unocss+reset@0.60.4_eslint@9.4.0_floating-vue@5.2.2_rol_kz5sis3zuyiqyo5au5yoh7bo4q/node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.8.0_@unocss+reset@0.60.4_eslint@9.4.0_floating-vue@5.2.2_rol_kz5sis3zuyiqyo5au5yoh7bo4q/node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.8.0_@unocss+reset@0.60.4_eslint@9.4.0_floating-vue@5.2.2_rol_kz5sis3zuyiqyo5au5yoh7bo4q/node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.8.0_@unocss+reset@0.60.4_eslint@9.4.0_floating-vue@5.2.2_rol_kz5sis3zuyiqyo5au5yoh7bo4q/node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.8.0_@unocss+reset@0.60.4_eslint@9.4.0_floating-vue@5.2.2_rol_kz5sis3zuyiqyo5au5yoh7bo4q/node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.8.0_@unocss+reset@0.60.4_eslint@9.4.0_floating-vue@5.2.2_rol_kz5sis3zuyiqyo5au5yoh7bo4q/node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.8.0_@unocss+reset@0.60.4_eslint@9.4.0_floating-vue@5.2.2_rol_kz5sis3zuyiqyo5au5yoh7bo4q/node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.8.0_@unocss+reset@0.60.4_eslint@9.4.0_floating-vue@5.2.2_rol_kz5sis3zuyiqyo5au5yoh7bo4q/node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.8.0_@unocss+reset@0.60.4_eslint@9.4.0_floating-vue@5.2.2_rol_kz5sis3zuyiqyo5au5yoh7bo4q/node_modules/nuxt/dist/head/runtime/components")['Body']
export const LazyCounter: typeof import("../components/Counter.vue")['default']
export const LazyDarkToggle: typeof import("../components/DarkToggle.vue")['default']
export const LazyFooter: typeof import("../components/Footer.vue")['default']
export const LazyInputEntry: typeof import("../components/InputEntry.vue")['default']
export const LazyLogos: typeof import("../components/Logos.vue")['default']
export const LazyPageView: typeof import("../components/PageView.vue")['default']
export const LazyUnoIcon: typeof import("../node_modules/.pnpm/@unocss+nuxt@0.60.4_postcss@8.4.38_rollup@2.79.1_vite@5.2.12_webpack@5.91.0/node_modules/@unocss/nuxt/runtime/UnoIcon.vue")['default']
export const LazyNuxtWelcome: typeof import("../node_modules/.pnpm/@nuxt+ui-templates@1.3.4/node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
export const LazyNuxtLayout: typeof import("../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.8.0_@unocss+reset@0.60.4_eslint@9.4.0_floating-vue@5.2.2_rol_kz5sis3zuyiqyo5au5yoh7bo4q/node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.8.0_@unocss+reset@0.60.4_eslint@9.4.0_floating-vue@5.2.2_rol_kz5sis3zuyiqyo5au5yoh7bo4q/node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.8.0_@unocss+reset@0.60.4_eslint@9.4.0_floating-vue@5.2.2_rol_kz5sis3zuyiqyo5au5yoh7bo4q/node_modules/nuxt/dist/app/components/client-only")['default']
export const LazyDevOnly: typeof import("../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.8.0_@unocss+reset@0.60.4_eslint@9.4.0_floating-vue@5.2.2_rol_kz5sis3zuyiqyo5au5yoh7bo4q/node_modules/nuxt/dist/app/components/dev-only")['default']
export const LazyServerPlaceholder: typeof import("../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.8.0_@unocss+reset@0.60.4_eslint@9.4.0_floating-vue@5.2.2_rol_kz5sis3zuyiqyo5au5yoh7bo4q/node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyNuxtLink: typeof import("../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.8.0_@unocss+reset@0.60.4_eslint@9.4.0_floating-vue@5.2.2_rol_kz5sis3zuyiqyo5au5yoh7bo4q/node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const LazyNuxtLoadingIndicator: typeof import("../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.8.0_@unocss+reset@0.60.4_eslint@9.4.0_floating-vue@5.2.2_rol_kz5sis3zuyiqyo5au5yoh7bo4q/node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const LazyNuxtIsland: typeof import("../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.8.0_@unocss+reset@0.60.4_eslint@9.4.0_floating-vue@5.2.2_rol_kz5sis3zuyiqyo5au5yoh7bo4q/node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyNuxtImg: typeof import("../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.8.0_@unocss+reset@0.60.4_eslint@9.4.0_floating-vue@5.2.2_rol_kz5sis3zuyiqyo5au5yoh7bo4q/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const LazyNuxtPicture: typeof import("../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.8.0_@unocss+reset@0.60.4_eslint@9.4.0_floating-vue@5.2.2_rol_kz5sis3zuyiqyo5au5yoh7bo4q/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const LazyColorScheme: typeof import("../node_modules/.pnpm/@nuxtjs+color-mode@3.4.1_rollup@2.79.1/node_modules/@nuxtjs/color-mode/dist/runtime/component.vue3.vue")['default']
export const LazyVitePwaManifest: typeof import("../node_modules/.pnpm/@vite-pwa+nuxt@0.7.0_rollup@2.79.1_vite@5.2.12_workbox-build@7.1.1_workbox-window@7.1.0/node_modules/@vite-pwa/nuxt/dist/runtime/components/VitePwaManifest")['default']
export const LazyNuxtPwaManifest: typeof import("../node_modules/.pnpm/@vite-pwa+nuxt@0.7.0_rollup@2.79.1_vite@5.2.12_workbox-build@7.1.1_workbox-window@7.1.0/node_modules/@vite-pwa/nuxt/dist/runtime/components/VitePwaManifest")['default']
export const LazyNuxtPwaAssets: typeof import("../node_modules/.pnpm/@vite-pwa+nuxt@0.7.0_rollup@2.79.1_vite@5.2.12_workbox-build@7.1.1_workbox-window@7.1.0/node_modules/@vite-pwa/nuxt/dist/runtime/components/NuxtPwaAssets")['default']
export const LazyPwaAppleImage: typeof import("../node_modules/.pnpm/@vite-pwa+nuxt@0.7.0_rollup@2.79.1_vite@5.2.12_workbox-build@7.1.1_workbox-window@7.1.0/node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaAppleImage.vue")['default']
export const LazyPwaAppleSplashScreenImage: typeof import("../node_modules/.pnpm/@vite-pwa+nuxt@0.7.0_rollup@2.79.1_vite@5.2.12_workbox-build@7.1.1_workbox-window@7.1.0/node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaAppleSplashScreenImage.vue")['default']
export const LazyPwaFaviconImage: typeof import("../node_modules/.pnpm/@vite-pwa+nuxt@0.7.0_rollup@2.79.1_vite@5.2.12_workbox-build@7.1.1_workbox-window@7.1.0/node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaFaviconImage.vue")['default']
export const LazyPwaMaskableImage: typeof import("../node_modules/.pnpm/@vite-pwa+nuxt@0.7.0_rollup@2.79.1_vite@5.2.12_workbox-build@7.1.1_workbox-window@7.1.0/node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaMaskableImage.vue")['default']
export const LazyPwaTransparentImage: typeof import("../node_modules/.pnpm/@vite-pwa+nuxt@0.7.0_rollup@2.79.1_vite@5.2.12_workbox-build@7.1.1_workbox-window@7.1.0/node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaTransparentImage.vue")['default']
export const LazyNuxtPage: typeof import("../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.8.0_@unocss+reset@0.60.4_eslint@9.4.0_floating-vue@5.2.2_rol_kz5sis3zuyiqyo5au5yoh7bo4q/node_modules/nuxt/dist/pages/runtime/page")['default']
export const LazyNoScript: typeof import("../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.8.0_@unocss+reset@0.60.4_eslint@9.4.0_floating-vue@5.2.2_rol_kz5sis3zuyiqyo5au5yoh7bo4q/node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const LazyLink: typeof import("../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.8.0_@unocss+reset@0.60.4_eslint@9.4.0_floating-vue@5.2.2_rol_kz5sis3zuyiqyo5au5yoh7bo4q/node_modules/nuxt/dist/head/runtime/components")['Link']
export const LazyBase: typeof import("../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.8.0_@unocss+reset@0.60.4_eslint@9.4.0_floating-vue@5.2.2_rol_kz5sis3zuyiqyo5au5yoh7bo4q/node_modules/nuxt/dist/head/runtime/components")['Base']
export const LazyTitle: typeof import("../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.8.0_@unocss+reset@0.60.4_eslint@9.4.0_floating-vue@5.2.2_rol_kz5sis3zuyiqyo5au5yoh7bo4q/node_modules/nuxt/dist/head/runtime/components")['Title']
export const LazyMeta: typeof import("../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.8.0_@unocss+reset@0.60.4_eslint@9.4.0_floating-vue@5.2.2_rol_kz5sis3zuyiqyo5au5yoh7bo4q/node_modules/nuxt/dist/head/runtime/components")['Meta']
export const LazyStyle: typeof import("../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.8.0_@unocss+reset@0.60.4_eslint@9.4.0_floating-vue@5.2.2_rol_kz5sis3zuyiqyo5au5yoh7bo4q/node_modules/nuxt/dist/head/runtime/components")['Style']
export const LazyHead: typeof import("../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.8.0_@unocss+reset@0.60.4_eslint@9.4.0_floating-vue@5.2.2_rol_kz5sis3zuyiqyo5au5yoh7bo4q/node_modules/nuxt/dist/head/runtime/components")['Head']
export const LazyHtml: typeof import("../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.8.0_@unocss+reset@0.60.4_eslint@9.4.0_floating-vue@5.2.2_rol_kz5sis3zuyiqyo5au5yoh7bo4q/node_modules/nuxt/dist/head/runtime/components")['Html']
export const LazyBody: typeof import("../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.8.0_@unocss+reset@0.60.4_eslint@9.4.0_floating-vue@5.2.2_rol_kz5sis3zuyiqyo5au5yoh7bo4q/node_modules/nuxt/dist/head/runtime/components")['Body']

export const componentNames: string[]
